# Generated by Django 3.1.7 on 2021-03-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='credits',
            new_name='created',
        ),
    ]
