# Generated by Django 3.1.7 on 2021-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0002_auto_20210302_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='bs2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='bs3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='bs4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='bs5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='bs6',
            field=models.IntegerField(null=True),
        ),
    ]
