# Generated by Django 3.1.7 on 2021-03-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0003_auto_20210302_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Himage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField(null=True)),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpPhoto', models.URLField(null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Himage',
            },
        ),
    ]
