# Generated by Django 3.1.7 on 2021-03-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0006_auto_20210309_1232'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='himage',
            table='Himage',
        ),
    ]
