# Generated by Django 3.1.7 on 2021-03-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0008_auto_20210309_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyimage',
            old_name='EmpPhoto',
            new_name='image',
        ),
    ]
