# Generated by Django 3.1.7 on 2021-03-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0009_auto_20210309_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyimage',
            name='EmpId',
        ),
    ]
